# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_quotes', to='retake.User'),
        ),
    ]
